server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_insert: true
          order_delete: true
          order_update: true
    hibernate:
      ddl-auto: update
    show-sql: true


indexing-settings:
  sites:
    - url: http://www.framenoir.com/
      name: Frame Noir
    - url: https://dombulgakova.ru/
      name: Дом Булгакова
    - url: https://playback.ru/
      name: PlayBack.Ru