services:
  web:
    image: search-engine
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/search_engine
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DB: search_engine
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d search_engine" ]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234